### ISSUE TITLE
Doing Nothing

### ISSUE THREAD

**Issue by comdoxx** [yaK2manD/qt-webview-pcsc#1]
Hi Alexandre,

this code isn't doing anything. Besides it displays a web page, that is missing within this project, there's nothing to make it start (i.e. "startRead(...)" method is not called.

Are you still developing this or did you just stop?

Either way: I'd like to make a qt-wrapper library for pcsc and think, this is a good start to do so. Did you do anything in that direction yet?

Regards,
Malte

**Comment by acorbel** [comment]
Hi, 
Yes I did not follow the QT dev. I switched to Java with JavaFx but it's been awhile :/
It was for a payment system and the html was loaded from another bundle.

This repo is only a kind of backup. But AFAIR, only the background worker and the reader methods worked.
